const defaults = {
    title: 'AcyOrt',
    description: 'A Node.js blog tool powered by GitHub.',
    keywords: 'nodejs, acyort, github',
    rss: 'rss.xml',
    favicon: 'favicon.ico',
    url: 'https://acyortjs.github.io',
    disqus: 'acyort',
    language: 'en',
    theme: 'ccc45',
    per_page: 3,
    archives_per_page: 30,
    thumbnail_mode: 2,
    menu: {
      archives: '/archives',
      category: '/category',
      tag: '/tag',
    },
    public_dir: '/',
    category_dir: 'category',
    tag_dir: 'tag',
    post_dir: 'posts',
    archives_dir: 'archives',
    default_category: 'uncategorized',
    user: 'acyortjs',
    repository: 'acyortjs.github.io',
    json: false,
    dev: false,
    authors: [],
    token: '',
}

module.exports = defaults
